### PR TITLE
(ISA-258) Story-maps Wordpress support

### PR DESCRIPTION
**Pull request by JoshGx2000**
[ISA-258](https://jira.its.utas.edu.au/browse/ISA-258)

This is the current plugin and child theme I'm using for testing the story-maps feature for Seamap. This is mainly placeholder for testing interoperability with the Seamap app. Custom post type requires use of [ACF](https://www.advancedcustomfields.com/). Theme is only designed for a single map link at the moment, rather than multiple, as multiple requires repeater group feature of ACF Pro.

### CODE REVIEW

**Comment by markhepburn** [comment]
Might as well document here rather than email/chat threads.. an alternative to ACF might be custom blocks.  Disclaimer: I know next to nothing about how they work except that wordpress is pushing everything in that direction anyway.  The main thing to test would be if the rendered fragments are accessible via the API, in the same way ACF is.

**Comment by JoshGx2000** [comment]
@markhepburn 
> Might as well document here rather than email/chat threads.. an alternative to ACF might be custom blocks. Disclaimer: I know next to nothing about how they work except that wordpress is pushing everything in that direction anyway. The main thing to test would be if the rendered fragments are accessible via the API, in the same way ACF is.

So before even touching on creating custom blocks, I took a look at how you can grab the rendered fragments in the api, and this is what I came up with.

Using ACF you get something like this (without junk)
```
{
    "title": {
        "rendered": "Pete&#8217;s Treasure"
    },
    "content": {
        "rendered": "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>",
        "protected": false
    },
    "acf": {
        "map_link": {
            "subtitle": "Group Name",
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
            "shortcode": "f98cd5df-8b7c-48ed-89df-7d1aef360dfc"
        }
    }
}
```

But with blocks, all the information is in `content: rendered:`
```
{
    "title": {
        "rendered": "Emma&#8217;s Trek"
    },
    "content": {
        "rendered": "
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        
        
        
        <div class="wp-container-3 is-vertical wp-block-group">
        <div class="wp-container-1 wp-block-group"><div class="wp-block-group__inner-container">
        <h2>Group 1</h2>
        
        
        
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        
        
        
        <p>f98cd5df-8b7c-48ed-89df-7d1aef360dfc</p>
        </div></div>
        
        
        
        <div class="wp-container-2 wp-block-group"><div class="wp-block-group__inner-container">
        <h2>Group 2</h2>
        
        
        
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        
        
        
        <p>dc183564-80e4-40e9-9e63-87ee0143947d</p>
        </div></div>
        </div>
        ",
        "protected": false
    }
}
```

What this means is if we went with blocks (even custom ones), we'd have to parse this markup for the bits we want, and even then it only works if posts are carefully curated to use the correct blocks in the correct order.

I haven't done too much digging into custom blocks yet, but maybe they are able to enforce only certain block types as children?

My personal preference is ACF.

**Comment by JoshGx2000** [comment]
Leaving this open until I get to registering the fields via PHP

**Comment by JoshGx2000** [comment]
The theme still needs to be updated to use the H-Code child theme template, but otherwise this is ready for merging. I leave it up to you @markhepburn for whether this should be merged now or later.

**Pull request merged**
