### PR TITLE
Feature: (ISA-214) Move tools to small controls

### PR DESCRIPTION
**Pull request by JoshGx2000**
[ISA-214](https://jira.its.utas.edu.au/browse/ISA-214)

This ended up being way less hacky then I thought it would in a lot of places; I thought I'd be having a lot of issues fighting with Leaflet Draw.
Omnisearch button also added.

Before:
Screen Shot 2022-08-04 at 1 23 23 pm
After:
Screen Shot 2022-08-04 at 1 22 18 pm

### CODE REVIEW

**Comment by markhepburn** [comment]
Only thing about the UI; did you experiment with combining the new buttons into a group at all?  (not sure if it's an improvement, but it looks a bit noisy/messy with the number of them)

**Review by markhepburn — APPROVED** [review]

**Comment by JoshGx2000** [comment]
> Only thing about the UI; did you experiment with combining the new buttons into a group at all? (not sure if it's an improvement, but it looks a bit noisy/messy with the number of them)
@markhepburn 
Just want to make sure I understand what you're suggesting; you're thinking of something export button where you can hover to reveal more options?
Screen Shot 2022-08-09 at 11 23 28 am

**Comment by markhepburn** [comment]
No, I was thinking like the "+6-" are grouped together.  Just to tidy things up, and group "random controls" together perhaps.

**Comment by JoshGx2000** [comment]
Ah, okay, I'll bring it up with Emma and I'll see what her thoughts on it are.

**Comment by markhepburn** [comment]
A screenshot for reference might help.

**Pull request merged**
